[package]
name = "ursa-major"
description = "Rogulike RPG"
version = "0.1.0"
authors = ["Krzysztof Langner <klangner@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/klangner/ursa-major"
edition = "2018"

[dependencies]
macroquad = "0.3"